#!/usr/bin/env bash
# Regenerate .github/requirements-build.txt with exact versions + sha256
# hashes so the release workflow can `pip install --require-hashes`.
#
# Run locally (needs network access to INDEX_URL):
#   bash .github/scripts/gen-build-hashes.sh
#
# Resolution is pinned to the release workflow's interpreter (TARGET_PY) and
# to pure-python wheels, so the output does not depend on which Python or OS
# the maintainer happens to run this from.

set -Eeuo pipefail

# Keep in sync with `python-version` in .github/workflows/release.yml.
TARGET_PY="${TARGET_PY:-3.10}"

# Resolve against whatever index pip is already configured to use (pip config
# global.index-url, PIP_INDEX_URL, ...), falling back to public PyPI when pip
# has no preference. Corp machines commonly pin an internal mirror and cannot
# reach pypi.org directly, while outside contributors get pypi.org; a mirror
# serves byte-identical artifacts, so the sha256 pins are valid whichever index
# resolved them. Force a specific index with:
#   INDEX_URL=https://pypi.org/simple bash .github/scripts/gen-build-hashes.sh
if [[ -z "${INDEX_URL:-}" ]]; then
  INDEX_URL="$(python -m pip config get global.index-url 2>/dev/null || echo 'https://pypi.org/simple')"
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IN_FILE="${REPO_ROOT}/.github/requirements-build.in"
OUT_FILE="${REPO_ROOT}/.github/requirements-build.txt"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# Resolve + download wheels only (no sdists -> stable hashes, no build step).
# --python-version/--implementation/--abi/--platform make the resolution match
# the CI runner rather than this machine; every build dep is py3-none-any.
python -m pip download \
  --index-url "$INDEX_URL" \
  --only-binary=:all: \
  --python-version "$TARGET_PY" \
  --implementation py \
  --abi none \
  --platform any \
  --dest "$WORK_DIR" \
  -r "$IN_FILE"

sha256() {
  python -c 'import hashlib,sys
with open(sys.argv[1], "rb") as fh:
    print(hashlib.file_digest(fh, "sha256").hexdigest() if hasattr(hashlib, "file_digest")
          else hashlib.sha256(fh.read()).hexdigest())' "$1"
}

{
  echo "# AUTO-GENERATED by .github/scripts/gen-build-hashes.sh -- do not edit by hand."
  echo "# Source: .github/requirements-build.in (resolved for Python ${TARGET_PY})"
  # The resolving index is deliberately NOT recorded here: this file is public
  # and the index is often an internal mirror. Mirrors serve byte-identical
  # artifacts, so the index does not change the pins below and is not needed to
  # reproduce them. It is echoed to the console instead.
  for whl in "$WORK_DIR"/*.whl; do
    base="$(basename "$whl")"
    # Wheel filename: {name}-{version}-{python}-{abi}-{platform}.whl, where
    # {name} has had '-' escaped to '_' (PEP 427).
    name="$(echo "$base" | cut -d- -f1 | tr '[:upper:]_' '[:lower:]-')"
    version="$(echo "$base" | cut -d- -f2)"
    echo "${name}==${version} --hash=sha256:$(sha256 "$whl")"
  done | sort
} > "$OUT_FILE"

echo "Wrote $OUT_FILE (resolved via ${INDEX_URL}):"
cat "$OUT_FILE"
