"""Databricks Asset Bundle rendering for Lakeflow Connect ingestion."""
import json
import re
from copy import deepcopy
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping, Tuple

import yaml

from databricks.labs.sdp_meta.lfc.renderer import IngestionRenderer


GENERATED_SUFFIX = ".ingestion.gen.yml"
BANNER = (
    "# GENERATED by sdp-meta from ingestion metadata. DO NOT EDIT.\n"
    "# Update the onboarding metadata and regenerate this file.\n\n"
)


def bundle_key(value: str) -> str:
    """Return an identifier-safe, deterministic DAB resource key."""
    key = re.sub(r"[^a-z0-9_]+", "_", str(value).strip().lower()).strip("_")
    if not key:
        raise ValueError("ingestion resource name must contain letters or digits")
    return key


def _value(spec: Any, *names: str, default: Any = None) -> Any:
    if isinstance(spec, Mapping):
        source = spec
    elif hasattr(spec, "__dict__"):
        source = vars(spec)
    else:
        raise TypeError("ingestion spec must be mapping-like")
    for name in names:
        if source.get(name) is not None:
            return source[name]
    return default


def _schedule(spec: Any) -> Dict[str, Any]:
    value = _value(spec, "schedule", default={})
    if isinstance(value, str):
        value = json.loads(value) if value else {}
    if not isinstance(value, Mapping):
        raise TypeError("ingestion schedule must be a map")
    return deepcopy(dict(value))


def build_pipeline_resources(
    spec: Any,
    renderer: IngestionRenderer = None,
) -> Dict[str, Dict[str, Any]]:
    """Build one gateway/ingestion pair and its optional schedule job."""
    rendered = (renderer or IngestionRenderer()).render(spec)
    if not rendered.deploy:
        return {"pipelines": {}, "jobs": {}}

    identity = _value(
        spec,
        "dataFlowGroup",
        "data_flow_group",
        "name",
        "dataFlowId",
        "data_flow_id",
    )
    key = bundle_key(identity)
    gateway_key = "lfc_%s_gateway" % key
    ingestion_key = "lfc_%s_ingestion" % key

    gateway = deepcopy(rendered.gateway)
    ingestion = deepcopy(rendered.ingestion)
    ingestion["ingestion_definition"]["ingestion_gateway_id"] = (
        "${resources.pipelines.%s.id}" % gateway_key
    )

    jobs = {}
    schedule = _schedule(spec)
    if schedule:
        job_key = "lfc_%s_schedule" % key
        jobs[job_key] = {
            "name": job_key,
            "schedule": schedule,
            "tasks": [{
                "task_key": "run_ingestion_pipeline",
                "pipeline_task": {
                    "pipeline_id": "${resources.pipelines.%s.id}" % ingestion_key,
                    "full_refresh": False,
                },
            }],
        }

    return {
        "pipelines": {
            gateway_key: gateway,
            ingestion_key: ingestion,
        },
        "jobs": jobs,
    }


def build_bundle_resources(specs: Iterable[Any]) -> Dict[str, Any]:
    """Merge multiple specs, rejecting normalized resource-key collisions."""
    pipelines = {}
    jobs = {}
    for spec in specs:
        resources = build_pipeline_resources(spec)
        for destination, additions in (
            (pipelines, resources["pipelines"]),
            (jobs, resources["jobs"]),
        ):
            collisions = set(destination).intersection(additions)
            if collisions:
                raise ValueError(
                    "duplicate ingestion bundle resource keys: %s"
                    % sorted(collisions)
                )
            destination.update(additions)
    result = {"pipelines": pipelines}
    if jobs:
        result["jobs"] = jobs
    return {"resources": result}


def render_bundle_resources(specs: Iterable[Any]) -> str:
    """Render deterministic bundle YAML for the supplied desired state."""
    body = yaml.safe_dump(
        build_bundle_resources(specs),
        sort_keys=False,
        default_flow_style=False,
        width=100,
    )
    return BANNER + body


def planned_files(
    specs: Iterable[Any],
    resources_dir: Path,
) -> Dict[str, Tuple[Path, str]]:
    """Plan one generated file per deployable ingestion pair."""
    result = {}
    for spec in specs:
        rendered = IngestionRenderer().render(spec)
        if not rendered.deploy:
            continue
        identity = _value(
            spec,
            "dataFlowGroup",
            "data_flow_group",
            "name",
            "dataFlowId",
            "data_flow_id",
        )
        key = bundle_key(identity)
        if key in result:
            raise ValueError("duplicate ingestion bundle key %r" % key)
        result[key] = (
            resources_dir / ("%s%s" % (key, GENERATED_SUFFIX)),
            render_bundle_resources([spec]),
        )
    return result
