baseURL = 'https://databrickslabs.github.io/sdp-meta/'
languageCode = 'en-us'
title = 'SDP-META'
theme= "hugo-theme-relearn"
pluralizeListTitles = false
canonifyURLs = true
description = "SDP-META Documentation"

[params]
    themeVariant = 'learn'
    themeVariantAuto = 'learn'
    disableShortcutsTitle = true
    disableLandingPageButton = false
    author.name = "Ravi Gawai (Databricks)"
    disableNextPrev = false